<?php

use Zend\Form\Element;

/** @var \Zend\Form\Form $form */

/** @var Element $username */
$username = $form->get('username');
$username->setAttribute('class', 'form-control');
$username->setAttribute('placeholder', 'Логин');

/** @var Element $password */
$password = $form->get('password');
$password->setAttribute('class', 'form-control');
$password->setAttribute('placeholder', 'Пароль');

$form->setAttribute('action', $this->url('admin/login', ['action' => 'login']));
$form->setAttribute('class', 'hm-editform');
$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class="form-group">
        <?= $this->formLabel($username) ?>
        <?= $this->formElement($username) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($password) ?>
        <?= $this->formElement($password) ?>
    </div>
<?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

if ($this->messages) {
    echo '<ul>';
    foreach ($this->messages as $message) {
        echo '<li>' . $message . '</li>';
    }
    echo '</ul>';
}